In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import statsmodels.api as sm

In [43]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [44]:
base = pd.read_csv("Blood Presssure Abnormality.csv")

In [45]:
base = base.drop(["Patient_Number"], axis = 1)

In [46]:
base.head(50)

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,11.28,0.90,34,23,1,1.0,0,45961,48071,NaN,2,1,1
1,0,9.75,0.23,54,33,1,NaN,0,26106,25333,205.0,3,0,0
2,1,10.79,0.91,70,49,0,NaN,0,9995,29465,67.0,2,1,0
3,0,11.00,0.43,71,50,0,NaN,0,10635,7439,242.0,1,1,0
4,1,14.17,0.83,52,19,0,NaN,0,15619,49644,397.0,2,0,0
5,0,11.64,0.54,23,48,0,NaN,1,27042,7513,NaN,3,0,0
6,1,11.69,0.75,43,41,1,1.0,0,38369,32967,206.0,3,1,1
7,0,12.70,0.41,48,20,0,NaN,0,29781,26749,134.0,2,0,0
8,0,10.88,0.68,72,44,0,NaN,0,814,9607,99.0,3,0,0
9,1,14.56,0.61,40,44,0,NaN,0,1278,12715,95.0,2,0,0
10,1,8.58,0.13,70,28,1,NaN,0,48527,26178,46.0,1,1,1
11,1,12.77,0.10,35,17,0,NaN,0,22500,43040,382.0,3,1,0
12,1,16.40,0.45,31,50,0,NaN,1,25639,46997,41.0,3,0,1
13,0,16.42,0.13,75,40,0,NaN,1,11750,49800,308.0,3,0,1
14,0,11.97,0.76,18,32,0,NaN,0,14562,18007,NaN,2,1,1
15,1,10.96,0.10,43,27,1,1.0,0,7329,39018,495.0,1,1,0
16,1,11.98,0.06,65,28,1,NaN,0,29834,45217,377.0,2,0,0
17,1,11.60,0.09,61,44,0,NaN,0,49430,36987,153.0,2,0,0
18,1,8.99,0.17,18,30,1,1.0,0,43934,35603,NaN,3,1,0
19,1,16.55,0.91,18,38,0,NaN,0,25466,1807,NaN,3,1,1
20,1,16.95,0.98,40,49,0,NaN,1,14976,16564,397.0,1,1,1
21,0,10.85,0.57,61,28,1,NaN,1,41119,12215,1.0,3,0,1
22,0,11.19,0.75,71,41,1,NaN,1,19422,21537,223.0,3,0,0
23,0,10.61,NaN,36,30,0,NaN,0,29724,19300,357.0,2,1,0
24,0,10.26,0.69,23,48,1,1.0,1,4861,25482,NaN,3,1,0
25,1,13.29,0.87,27,17,0,NaN,0,48477,18077,77.0,2,1,0
26,0,10.40,0.69,66,40,1,NaN,0,22277,14720,297.0,1,0,1
27,0,10.55,0.74,71,34,0,NaN,0,44478,2721,33.0,2,0,0
28,1,9.37,0.95,38,11,1,0.0,0,30738,48217,336.0,1,1,1
29,0,11.17,0.28,31,26,0,NaN,0,24834,1583,73.0,2,0,0
30,0,14.19,0.37,40,46,1,0.0,0,3922,39971,8.0,3,0,1
31,1,11.85,0.93,55,31,1,NaN,0,11788,30102,307.0,3,1,1
32,0,10.01,0.36,58,41,0,NaN,1,27985,30083,200.0,2,0,1
33,1,8.76,0.57,72,38,1,NaN,1,27249,40443,198.0,3,1,1
34,1,9.77,0.07,69,30,0,NaN,0,26185,37310,172.0,2,0,1
35,0,10.49,0.54,25,16,1,1.0,0,14798,26236,449.0,3,0,0
36,1,11.35,0.78,72,47,1,NaN,1,21038,9324,348.0,3,0,1
37,1,15.00,0.20,39,26,0,NaN,1,2907,34289,255.0,2,1,1
38,0,11.99,0.47,39,16,0,NaN,1,4854,40157,302.0,1,1,0
39,1,15.38,0.32,42,31,0,NaN,1,38123,5480,478.0,3,1,0
40,1,16.33,0.24,21,19,0,NaN,0,32576,8113,NaN,2,1,1
41,1,12.56,0.99,24,12,0,NaN,0,38769,2631,NaN,3,1,0
42,0,11.27,0.57,53,49,1,NaN,1,12184,35529,459.0,3,0,0
43,0,10.87,0.39,51,11,0,NaN,0,21226,34835,425.0,2,0,1
44,1,13.00,NaN,74,34,1,NaN,0,23274,2877,180.0,1,0,0
45,1,13.70,0.01,46,18,0,NaN,0,9982,23836,329.0,2,1,1
46,0,11.16,0.43,40,11,1,0.0,1,48799,20332,176.0,3,1,0
47,1,8.29,0.04,28,46,1,1.0,0,39998,24148,293.0,3,1,0
48,0,12.12,0.81,58,49,0,NaN,0,32570,38633,56.0,3,0,0
49,1,17.06,0.27,32,21,0,NaN,0,23703,33688,44.0,3,1,0

In [47]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Blood_Pressure_Abnormality     2000 non-null   int64
 1   Level_of_Hemoglobin            2000 non-null   float64
 2   Genetic_Pedigree_Coefficient   1908 non-null   float64
 3   Age                            2000 non-null   int64
 4   BMI                            2000 non-null   int64
 5   Sex                            2000 non-null   int64
 6   Pregnancy                      442 non-null    float64
 7   Smoking                        2000 non-null   int64
 8   Physical_activity              2000 non-null   int64
 9   salt_content_in_the_diet       2000 non-null   int64
 10  alcohol_consumption_per_day    1758 non-null   float64
 11  Level_of_Stress                2000 non-null   int64
 12  Chronic_kidney_disease         2000 non-null   int64
 13  Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(4), int64(10)
memory usage: 218.9 KB

In [48]:
base["Pregnancy"] = base["Pregnancy"].fillna(0)

In [49]:
base["alcohol_consumption_per_day"] = base["alcohol_consumption_per_day"].fillna((base["alcohol_consumption_per_day"].mean()))

In [50]:
base["Genetic_Pedigree_Coefficient"] = base["Genetic_Pedigree_Coefficient"].fillna((base["Genetic_Pedigree_Coefficient"].mean()))

In [51]:
base.describe()

,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,0.493500,11.710035,0.494817,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,251.008532,2.012500,0.5050,0.443500
std,0.500083,2.186701,0.284944,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,134.676187,0.823822,0.5001,0.496922
min,0.000000,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,0.000000,10.147500,0.250000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,144.000000,1.000000,0.0000,0.000000
50%,0.000000,11.330000,0.494817,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,251.008532,2.000000,1.0000,0.000000
75%,1.000000,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,1.000000,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

## Modelo de Regresion Logistica

In [52]:
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [53]:
y = base["Blood_Pressure_Abnormality"] #Variable dependiente
x = base.drop("Blood_Pressure_Abnormality", axis = 1) # La variables quitando la dependiente

In [54]:
y

0       1
1       0
2       1
3       0
4       1
5       0
6       1
7       0
8       0
9       1
10      1
11      1
12      1
13      0
14      0
15      1
16      1
17      1
18      1
19      1
20      1
21      0
22      0
23      0
24      0
25      1
26      0
27      0
28      1
29      0
30      0
31      1
32      0
33      1
34      1
35      0
36      1
37      1
38      0
39      1
40      1
41      1
42      0
43      0
44      1
45      1
46      0
47      1
48      0
49      1
50      0
51      1
52      1
53      0
54      1
55      0
56      0
57      1
58      1
59      1
60      0
61      0
62      1
63      0
64      1
65      0
66      0
67      0
68      0
69      1
70      0
71      1
72      1
73      1
74      0
75      1
76      1
77      0
78      1
79      1
80      0
81      0
82      1
83      0
84      1
85      0
86      0
87      0
88      0
89      0
90      0
91      1
92      1
93      1
94      0
95      0
96      0
97      1
98      1
99      1
100     1
101     1
102     0
103     1
104     1
105     0
106     0
107     1
108     1
109     0
110     0
111     1
112     0
113     0
114     1
115     0
116     1
117     1
118     0
119     0
120     0
121     1
122     1
123     0
124     0
125     1
126     0
127     1
128     1
129     1
130     0
131     0
132     1
133     1
134     0
135     0
136     0
137     1
138     1
139     1
140     0
141     1
142     1
143     1
144     0
145     1
146     1
147     1
148     1
149     0
150     1
151     0
152     1
153     1
154     0
155     0
156     0
157     0
158     1
159     1
160     0
161     0
162     1
163     0
164     1
165     1
166     0
167     0
168     1
169     0
170     0
171     0
172     1
173     0
174     0
175     0
176     0
177     1
178     1
179     0
180     1
181     0
182     0
183     1
184     0
185     1
186     1
187     1
188     0
189     0
190     0
191     0
192     1
193     1
194     1
195     1
196     0
197     1
198     0
199     1
200     1
201     0
202     0
203     0
204     1
205     0
206     0
207     1
208     0
209     1
210     1
211     1
212     1
213     1
214     0
215     0
216     1
217     0
218     1
219     1
220     1
221     1
222     0
223     1
224     0
225     0
226     1
227     0
228     1
229     0
230     0
231     0
232     1
233     0
234     1
235     0
236     0
237     0
238     1
239     0
240     1
241     0
242     0
243     1
244     0
245     1
246     1
247     0
248     1
249     0
250     0
251     0
252     1
253     0
254     1
255     0
256     0
257     0
258     1
259     0
260     0
261     0
262     0
263     0
264     0
265     0
266     0
267     1
268     0
269     0
270     0
271     1
272     0
273     0
274     1
275     1
276     0
277     0
278     0
279     0
280     0
281     1
282     1
283     0
284     0
285     0
286     1
287     1
288     1
289     1
290     1
291     0
292     0
293     1
294     0
295     1
296     0
297     0
298     0
299     0
300     1
301     1
302     0
303     0
304     0
305     0
306     0
307     1
308     1
309     0
310     0
311     1
312     0
313     1
314     0
315     1
316     1
317     1
318     0
319     0
320     0
321     0
322     1
323     0
324     0
325     0
326     0
327     1
328     1
329     0
330     1
331     1
332     0
333     1
334     1
335     1
336     1
337     0
338     1
339     1
340     0
341     1
342     0
343     0
344     0
345     0
346     0
347     0
348     1
349     0
350     1
351     1
352     0
353     1
354     0
355     0
356     1
357     0
358     0
359     1
360     1
361     0
362     0
363     1
364     0
365     1
366     0
367     0
368     1
369     1
370     0
371     1
372     0
373     0
374     1
375     1
376     0
377     1
378     0
379     0
380     1
381     0
382     0
383     1
384     1
385     1
386     1
387     0
388     0
389     1
390     1
391     1
392     0
393     1
394     0
395     0
396     0
397     1
398     1
399     1
400     1
401     0
402     1
403     0
404     0
405     0
406     0
407     1
408     1
409     0
410     1
411     1
412     0
413     0
414     0
415     1
416     0
417     0
418     0
419     1
420     0
421     0
422     0
423     1
424     1
425     0
426     1
427     1
428     0
429     1
430     1
431     1
432     0
433     1
434     1
435     0
436     1
437     0
438     0
439     1
440     0
441     1
442     1
443     0
444     1
445     0
446     0
447     0
448     0
449     1
450     1
451     1
452     0
453     0
454     1
455     0
456     1
457     1
458     0
459     0
460     0
461     1
462     0
463     0
464     0
465     0
466     1
467     1
468     1
469     1
470     1
471     1
472     1
473     0
474     1
475     1
476     0
477     0
478     0
479     1
480     1
481     0
482     1
483     1
484     0
485     0
486     1
487     1
488     1
489     1
490     1
491     0
492     0
493     1
494     1
495     0
496     0
497     1
498     1
499     0
500     0
501     1
502     0
503     0
504     0
505     1
506     0
507     1
508     1
509     1
510     0
511     1
512     1
513     1
514     0
515     0
516     1
517     0
518     0
519     0
520     1
521     1
522     1
523     0
524     0
525     0
526     0
527     0
528     0
529     1
530     1
531     1
532     0
533     0
534     0
535     0
536     1
537     0
538     1
539     1
540     1
541     0
542     1
543     1
544     0
545     0
546     0
547     1
548     1
549     0
550     1
551     1
552     1
553     1
554     1
555     0
556     1
557     1
558     1
559     1
560     0
561     1
562     0
563     0
564     1
565     0
566     0
567     1
568     1
569     0
570     0
571     1
572     1
573     0
574     0
575     1
576     0
577     0
578     1
579     1
580     1
581     1
582     1
583     0
584     0
585     0
586     0
587     0
588     0
589     1
590     1
591     0
592     1
593     0
594     0
595     1
596     1
597     1
598     0
599     1
600     0
601     0
602     0
603     0
604     1
605     1
606     1
607     1
608     0
609     0
610     0
611     0
612     0
613     0
614     0
615     0
616     1
617     1
618     1
619     0
620     0
621     0
622     0
623     0
624     0
625     1
626     1
627     1
628     1
629     0
630     0
631     1
632     1
633     0
634     0
635     0
636     0
637     0
638     0
639     1
640     0
641     1
642     1
643     1
644     0
645     0
646     0
647     1
648     1
649     0
650     1
651     0
652     0
653     1
654     1
655     1
656     1
657     1
658     0
659     0
660     0
661     0
662     1
663     0
664     0
665     0
666     0
667     0
668     0
669     1
670     0
671     1
672     0
673     0
674     0
675     0
676     0
677     0
678     0
679     0
680     1
681     1
682     1
683     1
684     1
685     1
686     0
687     1
688     0
689     0
690     1
691     1
692     0
693     1
694     1
695     0
696     0
697     0
698     1
699     0
700     1
701     1
702     1
703     0
704     0
705     0
706     1
707     0
708     0
709     1
710     1
711     0
712     0
713     1
714     0
715     0
716     0
717     1
718     0
719     1
720     1
721     0
722     0
723     0
724     0
725     1
726     1
727     1
728     0
729     1
730     0
731     0
732     1
733     0
734     0
735     1
736     0
737     0
738     1
739     0
740     0
741     0
742     0
743     0
744     0
745     1
746     0
747     0
748     1
749     1
750     0
751     0
752     1
753     0
754     0
755     0
756     1
757     1
758     0
759     1
760     0
761     0
762     0
763     1
764     0
765     1
766     0
767     0
768     1
769     1
770     1
771     1
772     0
773     1
774     1
775     0
776     1
777     1
778     1
779     1
780     1
781     0
782     0
783     1
784     0
785     0
786     0
787     0
788     1
789     0
790     0
791     0
792     1
793     0
794     1
795     0
796     1
797     0
798     0
799     1
800     0
801     0
802     1
803     0
804     1
805     0
806     0
807     0
808     0
809     0
810     0
811     1
812     0
813     1
814     0
815     1
816     0
817     0
818     0
819     0
820     0
821     1
822     0
823     0
824     1
825     0
826     0
827     1
828     1
829     1
830     0
831     0
832     0
833     1
834     0
835     1
836     1
837     0
838     0
839     0
840     1
841     0
842     0
843     1
844     0
845     1
846     1
847     0
848     0
849     0
850     1
851     0
852     1
853     1
854     1
855     0
856     0
857     0
858     1
859     1
860     1
861     0
862     1
863     1
864     1
865     1
866     1
867     0
868     1
869     0
870     1
871     0
872     0
873     1
874     0
875     0
876     0
877     1
878     1
879     1
880     0
881     1
882     0
883     1
884     0
885     0
886     1
887     0
888     0
889     0
890     0
891     1
892     0
893     1
894     1
895     0
896     0
897     0
898     1
899     1
900     1
901     1
902     0
903     0
904     1
905     0
906     0
907     1
908     1
909     0
910     1
911     1
912     1
913     0
914     0
915     1
916     0
917     1
918     1
919     1
920     0
921     1
922     0
923     1
924     0
925     0
926     1
927     0
928     1
929     0
930     1
931     0
932     1
933     0
934     1
935     1
936     0
937     0
938     0
939     0
940     0
941     1
942     0
943     0
944     0
945     1
946     0
947     1
948     0
949     0
950     1
951     0
952     0
953     1
954     1
955     0
956     1
957     1
958     0
959     1
960     1
961     1
962     1
963     1
964     1
965     0
966     1
967     1
968     0
969     1
970     1
971     1
972     1
973     1
974     1
975     1
976     0
977     1
978     0
979     1
980     1
981     1
982     1
983     0
984     1
985     1
986     0
987     0
988     1
989     1
990     1
991     1
992     0
993     1
994     0
995     0
996     1
997     0
998     1
999     1
1000    0
1001    1
1002    0
1003    1
1004    1
1005    0
1006    0
1007    1
1008    0
1009    0
1010    1
1011    1
1012    1
1013    1
1014    1
1015    1
1016    1
1017    1
1018    0
1019    1
1020    0
1021    0
1022    0
1023    1
1024    1
1025    0
1026    1
1027    0
1028    0
1029    1
1030    0
1031    1
1032    1
1033    0
1034    1
1035    0
1036    1
1037    0
1038    1
1039    0
1040    1
1041    1
1042    1
1043    0
1044    0
1045    0
1046    1
1047    1
1048    1
1049    1
1050    1
1051    0
1052    0
1053    1
1054    0
1055    1
1056    0
1057    0
1058    0
1059    1
1060    0
1061    1
1062    0
1063    0
1064    0
1065    0
1066    0
1067    0
1068    0
1069    0
1070    1
1071    1
1072    0
1073    1
1074    1
1075    0
1076    0
1077    1
1078    1
1079    1
1080    0
1081    1
1082    0
1083    0
1084    1
1085    1
1086    1
1087    0
1088    0
1089    0
1090    0
1091    0
1092    1
1093    1
1094    0
1095    1
1096    1
1097    0
1098    0
1099    1
1100    0
1101    0
1102    0
1103    1
1104    0
1105    0
1106    1
1107    1
1108    1
1109    0
1110    1
1111    1
1112    1
1113    0
1114    1
1115    1
1116    1
1117    0
1118    1
1119    1
1120    0
1121    1
1122    1
1123    0
1124    1
1125    1
1126    1
1127    0
1128    0
1129    1
1130    1
1131    0
1132    0
1133    1
1134    1
1135    1
1136    1
1137    0
1138    1
1139    0
1140    1
1141    0
1142    1
1143    0
1144    0
1145    1
1146    0
1147    0
1148    1
1149    0
1150    1
1151    1
1152    0
1153    0
1154    1
1155    1
1156    0
1157    1
1158    0
1159    0
1160    0
1161    0
1162    1
1163    1
1164    1
1165    0
1166    1
1167    1
1168    1
1169    0
1170    1
1171    1
1172    0
1173    0
1174    1
1175    0
1176    1
1177    0
1178    1
1179    1
1180    1
1181    1
1182    1
1183    0
1184    1
1185    0
1186    0
1187    0
1188    0
1189    1
1190    1
1191    1
1192    1
1193    0
1194    0
1195    0
1196    1
1197    0
1198    0
1199    1
1200    1
1201    1
1202    0
1203    1
1204    1
1205    1
1206    1
1207    0
1208    1
1209    0
1210    1
1211    1
1212    1
1213    1
1214    0
1215    1
1216    1
1217    1
1218    1
1219    1
1220    1
1221    0
1222    1
1223    0
1224    0
1225    1
1226    0
1227    1
1228    1
1229    0
1230    1
1231    1
1232    1
1233    0
1234    0
1235    0
1236    0
1237    0
1238    0
1239    0
1240    0
1241    1
1242    0
1243    1
1244    1
1245    0
1246    1
1247    0
1248    1
1249    0
1250    0
1251    1
1252    0
1253    1
1254    1
1255    0
1256    0
1257    1
1258    0
1259    0
1260    1
1261    1
1262    1
1263    1
1264    1
1265    0
1266    0
1267    1
1268    0
1269    0
1270    0
1271    1
1272    0
1273    0
1274    1
1275    1
1276    1
1277    0
1278    1
1279    1
1280    0
1281    0
1282    1
1283    0
1284    1
1285    0
1286    1
1287    0
1288    1
1289    0
1290    0
1291    0
1292    1
1293    1
1294    1
1295    1
1296    1
1297    1
1298    0
1299    1
1300    1
1301    1
1302    1
1303    1
1304    1
1305    0
1306    1
1307    0
1308    0
1309    0
1310    1
1311    0
1312    0
1313    0
1314    0
1315    0
1316    1
1317    1
1318    1
1319    1
1320    1
1321    0
1322    0
1323    1
1324    0
1325    0
1326    0
1327    1
1328    0
1329    1
1330    0
1331    0
1332    0
1333    0
1334    0
1335    1
1336    1
1337    1
1338    0
1339    1
1340    0
1341    1
1342    1
1343    0
1344    1
1345    1
1346    1
1347    0
1348    0
1349    0
1350    1
1351    1
1352    1
1353    1
1354    1
1355    0
1356    0
1357    0
1358    0
1359    1
1360    1
1361    0
1362    1
1363    0
1364    0
1365    0
1366    1
1367    0
1368    0
1369    0
1370    0
1371    1
1372    1
1373    0
1374    1
1375    1
1376    0
1377    0
1378    1
1379    1
1380    0
1381    0
1382    1
1383    0
1384    1
1385    0
1386    1
1387    1
1388    0
1389    0
1390    1
1391    0
1392    1
1393    1
1394    1
1395    0
1396    1
1397    0
1398    0
1399    0
1400    1
1401    1
1402    1
1403    0
1404    1
1405    1
1406    0
1407    0
1408    0
1409    0
1410    1
1411    0
1412    0
1413    1
1414    0
1415    0
1416    0
1417    0
1418    0
1419    1
1420    1
1421    1
1422    0
1423    1
1424    1
1425    0
1426    1
1427    0
1428    1
1429    1
1430    0
1431    0
1432    1
1433    0
1434    0
1435    1
1436    0
1437    0
1438    0
1439    1
1440    1
1441    0
1442    0
1443    1
1444    0
1445    1
1446    1
1447    1
1448    1
1449    0
1450    0
1451    0
1452    1
1453    1
1454    0
1455    1
1456    0
1457    0
1458    0
1459    0
1460    0
1461    0
1462    0
1463    1
1464    1
1465    0
1466    1
1467    1
1468    1
1469    0
1470    1
1471    1
1472    1
1473    1
1474    1
1475    1
1476    0
1477    1
1478    1
1479    0
1480    0
1481    1
1482    1
1483    1
1484    0
1485    0
1486    0
1487    0
1488    0
1489    0
1490    1
1491    0
1492    1
1493    1
1494    1
1495    1
1496    1
1497    0
1498    1
1499    1
1500    1
1501    1
1502    0
1503    1
1504    1
1505    0
1506    0
1507    0
1508    1
1509    1
1510    1
1511    0
1512    1
1513    1
1514    1
1515    0
1516    1
1517    1
1518    1
1519    1
1520    1
1521    1
1522    0
1523    1
1524    0
1525    1
1526    0
1527    0
1528    1
1529    1
1530    1
1531    1
1532    1
1533    1
1534    0
1535    0
1536    1
1537    1
1538    0
1539    0
1540    1
1541    1
1542    0
1543    0
1544    0
1545    1
1546    0
1547    1
1548    1
1549    1
1550    1
1551    1
1552    1
1553    1
1554    1
1555    0
1556    0
1557    1
1558    1
1559    1
1560    1
1561    0
1562    1
1563    0
1564    1
1565    0
1566    0
1567    0
1568    0
1569    0
1570    1
1571    1
1572    1
1573    1
1574    0
1575    0
1576    0
1577    0
1578    1
1579    1
1580    0
1581    1
1582    0
1583    0
1584    0
1585    0
1586    1
1587    0
1588    0
1589    1
1590    0
1591    1
1592    0
1593    0
1594    1
1595    0
1596    1
1597    0
1598    1
1599    1
1600    1
1601    0
1602    0
1603    0
1604    0
1605    1
1606    0
1607    0
1608    0
1609    0
1610    0
1611    1
1612    0
1613    1
1614    1
1615    1
1616    0
1617    1
1618    0
1619    0
1620    0
1621    1
1622    1
1623    0
1624    0
1625    1
1626    1
1627    0
1628    1
1629    0
1630    1
1631    0
1632    1
1633    1
1634    0
1635    1
1636    0
1637    0
1638    1
1639    0
1640    1
1641    0
1642    0
1643    1
1644    0
1645    1
1646    1
1647    0
1648    1
1649    0
1650    1
1651    1
1652    0
1653    1
1654    0
1655    1
1656    0
1657    0
1658    0
1659    1
1660    0
1661    0
1662    0
1663    1
1664    1
1665    0
1666    0
1667    1
1668    1
1669    1
1670    1
1671    0
1672    0
1673    1
1674    1
1675    1
1676    0
1677    0
1678    0
1679    1
1680    1
1681    0
1682    1
1683    1
1684    0
1685    0
1686    0
1687    0
1688    1
1689    1
1690    1
1691    1
1692    0
1693    0
1694    0
1695    0
1696    1
1697    1
1698    1
1699    1
1700    0
1701    0
1702    1
1703    0
1704    0
1705    0
1706    1
1707    0
1708    1
1709    1
1710    0
1711    1
1712    0
1713    0
1714    1
1715    1
1716    0
1717    1
1718    1
1719    0
1720    1
1721    0
1722    1
1723    1
1724    1
1725    0
1726    1
1727    1
1728    0
1729    1
1730    0
1731    1
1732    0
1733    0
1734    1
1735    0
1736    0
1737    1
1738    0
1739    0
1740    1
1741    0
1742    0
1743    1
1744    1
1745    1
1746    0
1747    0
1748    0
1749    1
1750    0
1751    1
1752    1
1753    1
1754    0
1755    1
1756    0
1757    0
1758    0
1759    0
1760    0
1761    1
1762    1
1763    1
1764    0
1765    1
1766    0
1767    0
1768    0
1769    1
1770    0
1771    0
1772    1
1773    0
1774    1
1775    0
1776    0
1777    0
1778    1
1779    0
1780    0
1781    1
1782    0
1783    1
1784    1
1785    1
1786    1
1787    1
1788    0
1789    1
1790    0
1791    0
1792    0
1793    0
1794    0
1795    0
1796    1
1797    1
1798    0
1799    1
1800    0
1801    1
1802    0
1803    0
1804    0
1805    0
1806    0
1807    1
1808    0
1809    0
1810    1
1811    1
1812    0
1813    0
1814    0
1815    0
1816    0
1817    0
1818    0
1819    0
1820    0
1821    0
1822    1
1823    0
1824    1
1825    1
1826    1
1827    1
1828    1
1829    1
1830    0
1831    0
1832    0
1833    0
1834    0
1835    1
1836    0
1837    1
1838    0
1839    1
1840    0
1841    0
1842    1
1843    1
1844    0
1845    1
1846    1
1847    1
1848    0
1849    1
1850    0
1851    1
1852    0
1853    1
1854    0
1855    0
1856    1
1857    1
1858    1
1859    0
1860    1
1861    1
1862    1
1863    1
1864    1
1865    0
1866    0
1867    0
1868    0
1869    1
1870    0
1871    0
1872    1
1873    1
1874    1
1875    0
1876    0
1877    1
1878    1
1879    1
1880    0
1881    0
1882    0
1883    1
1884    0
1885    0
1886    0
1887    0
1888    1
1889    1
1890    1
1891    1
1892    1
1893    1
1894    1
1895    0
1896    1
1897    0
1898    0
1899    1
1900    1
1901    0
1902    1
1903    1
1904    1
1905    0
1906    1
1907    0
1908    1
1909    0
1910    0
1911    1
1912    0
1913    1
1914    1
1915    1
1916    0
1917    1
1918    0
1919    0
1920    0
1921    0
1922    0
1923    0
1924    1
1925    0
1926    1
1927    0
1928    1
1929    1
1930    1
1931    1
1932    0
1933    1
1934    0
1935    1
1936    0
1937    0
1938    1
1939    0
1940    1
1941    1
1942    1
1943    0
1944    1
1945    1
1946    1
1947    0
1948    0
1949    1
1950    1
1951    0
1952    1
1953    1
1954    0
1955    1
1956    1
1957    0
1958    0
1959    0
1960    1
1961    0
1962    0
1963    0
1964    0
1965    0
1966    0
1967    0
1968    1
1969    1
1970    1
1971    0
1972    0
1973    1
1974    1
1975    1
1976    0
1977    0
1978    0
1979    0
1980    0
1981    1
1982    0
1983    1
1984    0
1985    0
1986    1
1987    1
1988    1
1989    1
1990    1
1991    1
1992    1
1993    0
1994    0
1995    1
1996    1
1997    1
1998    0
1999    1

In [55]:
x.head(5)

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,11.28,0.90,34,23,1,1.0,0,45961,48071,251.008532,2,1,1
1,9.75,0.23,54,33,1,0.0,0,26106,25333,205.000000,3,0,0
2,10.79,0.91,70,49,0,0.0,0,9995,29465,67.000000,2,1,0
3,11.00,0.43,71,50,0,0.0,0,10635,7439,242.000000,1,1,0
4,14.17,0.83,52,19,0,0.0,0,15619,49644,397.000000,2,0,0

In [56]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(x,y,test_size = 0.2, random_state = 2)

In [57]:
x_train.describe()

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,1600.000000,1600.000000,1600.000000,1600.000000,1600.000000,1600.00000,1600.000000,1600.000000,1600.000000,1600.000000,1600.000000,1600.000000,1600.000000
mean,11.693750,0.490801,46.568750,30.056875,0.491875,0.09750,0.504375,25410.320625,24821.042500,249.202322,2.020625,0.503750,0.448750
std,2.198172,0.285046,17.218902,11.716631,0.500090,0.29673,0.500137,13977.898799,14147.248072,133.868224,0.825758,0.500142,0.497522
min,8.100000,0.000000,18.000000,10.000000,0.000000,0.00000,0.000000,628.000000,22.000000,0.000000,1.000000,0.000000,0.000000
25%,10.107500,0.250000,32.000000,20.000000,0.000000,0.00000,0.000000,13790.250000,13334.000000,145.750000,1.000000,0.000000,0.000000
50%,11.325000,0.494817,46.500000,30.000000,0.000000,0.00000,1.000000,25451.500000,24868.000000,251.008532,2.000000,1.000000,0.000000
75%,12.925000,0.720000,62.000000,40.000000,1.000000,0.00000,1.000000,37448.250000,36723.250000,355.000000,3.000000,1.000000,1.000000
max,17.560000,1.000000,75.000000,50.000000,1.000000,1.00000,1.000000,49940.000000,49976.000000,499.000000,3.000000,1.000000,1.000000

In [58]:
x.describe()

,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,Physical_activity,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,11.710035,0.494817,46.558500,30.081500,0.496000,0.099500,0.509500,25254.424500,24926.097000,251.008532,2.012500,0.5050,0.443500
std,2.186701,0.284944,17.107832,11.761208,0.500109,0.299407,0.500035,14015.439623,14211.692586,134.676187,0.823822,0.5001,0.496922
min,8.100000,0.000000,18.000000,10.000000,0.000000,0.000000,0.000000,628.000000,22.000000,0.000000,1.000000,0.0000,0.000000
25%,10.147500,0.250000,32.000000,20.000000,0.000000,0.000000,0.000000,13605.750000,13151.750000,144.000000,1.000000,0.0000,0.000000
50%,11.330000,0.494817,46.000000,30.000000,0.000000,0.000000,1.000000,25353.000000,25046.500000,251.008532,2.000000,1.0000,0.000000
75%,12.945000,0.730000,62.000000,40.000000,1.000000,0.000000,1.000000,37382.250000,36839.750000,360.250000,3.000000,1.0000,1.000000
max,17.560000,1.000000,75.000000,50.000000,1.000000,1.000000,1.000000,49980.000000,49976.000000,499.000000,3.000000,1.0000,1.000000

In [59]:
y_train.sum()/len(y_train)

0.49375

In [60]:
y_test.sum()/len(y_test)

0.4925

## Cross Validation

In [61]:
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\hvela\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [62]:
model = LogisticRegression(solver="liblinear")
model.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [63]:
predict = model.predict(x_test)

In [64]:
# Factor de exito del modelo
score = model.score(x_test,y_test)
print(score)

0.7

### Evaluacion del modelo

In [65]:
pd.crosstab(y_test,predict)

col_0                         0    1
Blood_Pressure_Abnormality
0                           141   62
1                            58  139

In [66]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.71      0.69      0.70       203
           1       0.69      0.71      0.70       197

    accuracy                           0.70       400
   macro avg       0.70      0.70      0.70       400
weighted avg       0.70      0.70      0.70       400

In [67]:
model.coef_

array([[ 1.54794186e-01, -6.56576088e-01, -5.42054634e-03,
        -1.98043447e-03,  5.46090566e-01,  2.62861330e-02,
         1.85744122e-02,  8.26061642e-06, -6.56330815e-07,
         6.06868532e-05,  2.53051390e-02,  1.88503165e+00,
         1.38085455e+00]])

In [68]:
import numpy as np

In [69]:
pd.DataFrame(list(zip(x.columns,np.transpose(model.coef_))))

                                0                         1
0             Level_of_Hemoglobin     [0.15479418618004576]
1    Genetic_Pedigree_Coefficient     [-0.6565760883579588]
2                             Age   [-0.005420546343323341]
3                             BMI   [-0.001980434473994233]
4                             Sex      [0.5460905656489917]
5                       Pregnancy     [0.02628613303414908]
6                         Smoking    [0.018574412222200756]
7               Physical_activity    [8.26061641665175e-06]
8        salt_content_in_the_diet  [-6.563308148220233e-07]
9     alcohol_consumption_per_day  [6.0686853192340516e-05]
10                Level_of_Stress    [0.025305138973477446]
11         Chronic_kidney_disease      [1.8850316499120792]
12  Adrenal_and_thyroid_disorders      [1.3808545498445788]

In [70]:
# Crear una variable para las porbabilidades 
probs = model.predict_proba(x_test)

In [71]:
probs

array([[0.81398285, 0.18601715],
       [0.85590211, 0.14409789],
       [0.45251364, 0.54748636],
       [0.10782139, 0.89217861],
       [0.41520012, 0.58479988],
       [0.50568633, 0.49431367],
       [0.25855776, 0.74144224],
       [0.48540097, 0.51459903],
       [0.64896863, 0.35103137],
       [0.4063297 , 0.5936703 ],
       [0.87366064, 0.12633936],
       [0.41938981, 0.58061019],
       [0.61669778, 0.38330222],
       [0.86838878, 0.13161122],
       [0.84258076, 0.15741924],
       [0.48196446, 0.51803554],
       [0.20725215, 0.79274785],
       [0.16457932, 0.83542068],
       [0.38613318, 0.61386682],
       [0.71220132, 0.28779868],
       [0.18884091, 0.81115909],
       [0.81956386, 0.18043614],
       [0.46364987, 0.53635013],
       [0.20468227, 0.79531773],
       [0.89761486, 0.10238514],
       [0.84661047, 0.15338953],
       [0.15508303, 0.84491697],
       [0.56424009, 0.43575991],
       [0.35864001, 0.64135999],
       [0.20346679, 0.79653321],
       [0.45258662, 0.54741338],
       [0.36968034, 0.63031966],
       [0.82545509, 0.17454491],
       [0.64029295, 0.35970705],
       [0.29137808, 0.70862192],
       [0.31937403, 0.68062597],
       [0.10745662, 0.89254338],
       [0.60625428, 0.39374572],
       [0.18411867, 0.81588133],
       [0.16636282, 0.83363718],
       [0.44246922, 0.55753078],
       [0.20182596, 0.79817404],
       [0.44831253, 0.55168747],
       [0.79298728, 0.20701272],
       [0.40386565, 0.59613435],
       [0.85908451, 0.14091549],
       [0.71628045, 0.28371955],
       [0.15322076, 0.84677924],
       [0.85225513, 0.14774487],
       [0.27831489, 0.72168511],
       [0.13312555, 0.86687445],
       [0.11030725, 0.88969275],
       [0.12636482, 0.87363518],
       [0.32070652, 0.67929348],
       [0.78425305, 0.21574695],
       [0.5250144 , 0.4749856 ],
       [0.89117366, 0.10882634],
       [0.52396737, 0.47603263],
       [0.08519764, 0.91480236],
       [0.85753895, 0.14246105],
       [0.16017652, 0.83982348],
       [0.12975985, 0.87024015],
       [0.47651543, 0.52348457],
       [0.62452522, 0.37547478],
       [0.84557816, 0.15442184],
       [0.13848918, 0.86151082],
       [0.91612792, 0.08387208],
       [0.09910697, 0.90089303],
       [0.2651817 , 0.7348183 ],
       [0.86595852, 0.13404148],
       [0.1119059 , 0.8880941 ],
       [0.32118911, 0.67881089],
       [0.36665697, 0.63334303],
       [0.77406175, 0.22593825],
       [0.85279962, 0.14720038],
       [0.81280634, 0.18719366],
       [0.86944716, 0.13055284],
       [0.15067431, 0.84932569],
       [0.51210496, 0.48789504],
       [0.82736457, 0.17263543],
       [0.87659754, 0.12340246],
       [0.61168394, 0.38831606],
       [0.21609326, 0.78390674],
       [0.20101339, 0.79898661],
       [0.40098528, 0.59901472],
       [0.37339992, 0.62660008],
       [0.11307804, 0.88692196],
       [0.19473913, 0.80526087],
       [0.50904458, 0.49095542],
       [0.81452298, 0.18547702],
       [0.76464175, 0.23535825],
       [0.18917622, 0.81082378],
       [0.8236225 , 0.1763775 ],
       [0.72938641, 0.27061359],
       [0.84124314, 0.15875686],
       [0.4358394 , 0.5641606 ],
       [0.54368017, 0.45631983],
       [0.32169438, 0.67830562],
       [0.84265263, 0.15734737],
       [0.87410663, 0.12589337],
       [0.18143927, 0.81856073],
       [0.3885695 , 0.6114305 ],
       [0.38678426, 0.61321574],
       [0.42218034, 0.57781966],
       [0.14740168, 0.85259832],
       [0.30603544, 0.69396456],
       [0.4723448 , 0.5276552 ],
       [0.0687414 , 0.9312586 ],
       [0.6414363 , 0.3585637 ],
       [0.09714799, 0.90285201],
       [0.6820412 , 0.3179588 ],
       [0.8625756 , 0.1374244 ],
       [0.12594721, 0.87405279],
       [0.39421729, 0.60578271],
       [0.40111621, 0.59888379],
       [0.84008534, 0.15991466],
       [0.50153305, 0.49846695],
       [0.28649079, 0.71350921],
       [0.535346  , 0.464654  ],
       [0.83425368, 0.16574632],
       [0.12803598, 0.87196402],
       [0.76643268, 0.23356732],
       [0.12295916, 0.87704084],
       [0.13342646, 0.86657354],
       [0.80879686, 0.19120314],
       [0.4374646 , 0.5625354 ],
       [0.61084868, 0.38915132],
       [0.89178619, 0.10821381],
       [0.35501894, 0.64498106],
       [0.47039767, 0.52960233],
       [0.8038571 , 0.1961429 ],
       [0.4949076 , 0.5050924 ],
       [0.10603379, 0.89396621],
       [0.87316567, 0.12683433],
       [0.67005414, 0.32994586],
       [0.17380327, 0.82619673],
       [0.81581805, 0.18418195],
       [0.6709189 , 0.3290811 ],
       [0.86760606, 0.13239394],
       [0.56098419, 0.43901581],
       [0.18077347, 0.81922653],
       [0.20546272, 0.79453728],
       [0.59323637, 0.40676363],
       [0.14942911, 0.85057089],
       [0.53861418, 0.46138582],
       [0.65352579, 0.34647421],
       [0.77883077, 0.22116923],
       [0.23777561, 0.76222439],
       [0.40588027, 0.59411973],
       [0.08190293, 0.91809707],
       [0.18966657, 0.81033343],
       [0.48831439, 0.51168561],
       [0.23743619, 0.76256381],
       [0.50673047, 0.49326953],
       [0.31489303, 0.68510697],
       [0.79591624, 0.20408376],
       [0.43049194, 0.56950806],
       [0.33361738, 0.66638262],
       [0.08439409, 0.91560591],
       [0.53628957, 0.46371043],
       [0.79754421, 0.20245579],
       [0.09047506, 0.90952494],
       [0.18956752, 0.81043248],
       [0.36833423, 0.63166577],
       [0.41412974, 0.58587026],
       [0.11669819, 0.88330181],
       [0.59733239, 0.40266761],
       [0.8668383 , 0.1331617 ],
       [0.43349556, 0.56650444],
       [0.19161319, 0.80838681],
       [0.31261086, 0.68738914],
       [0.60503142, 0.39496858],
       [0.81774781, 0.18225219],
       [0.53833016, 0.46166984],
       [0.72217249, 0.27782751],
       [0.29045064, 0.70954936],
       [0.47784284, 0.52215716],
       [0.82509832, 0.17490168],
       [0.4803345 , 0.5196655 ],
       [0.3051175 , 0.6948825 ],
       [0.18544911, 0.81455089],
       [0.65946147, 0.34053853],
       [0.13926133, 0.86073867],
       [0.59436491, 0.40563509],
       [0.68366735, 0.31633265],
       [0.14909611, 0.85090389],
       [0.73723957, 0.26276043],
       [0.14942784, 0.85057216],
       [0.19039538, 0.80960462],
       [0.4918836 , 0.5081164 ],
       [0.15213935, 0.84786065],
       [0.87604057, 0.12395943],
       [0.76548016, 0.23451984],
       [0.13883505, 0.86116495],
       [0.34725432, 0.65274568],
       [0.14146993, 0.85853007],
       [0.47415128, 0.52584872],
       [0.82676859, 0.17323141],
       [0.64407048, 0.35592952],
       [0.65854227, 0.34145773],
       [0.53302308, 0.46697692],
       [0.54644405, 0.45355595],
       [0.46866433, 0.53133567],
       [0.88911591, 0.11088409],
       [0.81447886, 0.18552114],
       [0.37923842, 0.62076158],
       [0.83712807, 0.16287193],
       [0.25536305, 0.74463695],
       [0.50377138, 0.49622862],
       [0.45908962, 0.54091038],
       [0.39994733, 0.60005267],
       [0.17979289, 0.82020711],
       [0.28777326, 0.71222674],
       [0.13115471, 0.86884529],
       [0.80657843, 0.19342157],
       [0.23868314, 0.76131686],
       [0.81603134, 0.18396866],
       [0.17471553, 0.82528447],
       [0.698967  , 0.301033  ],
       [0.64938627, 0.35061373],
       [0.75503417, 0.24496583],
       [0.04834325, 0.95165675],
       [0.38598239, 0.61401761],
       [0.13670758, 0.86329242],
       [0.14673732, 0.85326268],
       [0.50955714, 0.49044286],
       [0.85801257, 0.14198743],
       [0.6478945 , 0.3521055 ],
       [0.36573076, 0.63426924],
       [0.60218992, 0.39781008],
       [0.77196612, 0.22803388],
       [0.26639408, 0.73360592],
       [0.29947605, 0.70052395],
       [0.81532188, 0.18467812],
       [0.42116302, 0.57883698],
       [0.22970669, 0.77029331],
       [0.88500222, 0.11499778],
       [0.79636489, 0.20363511],
       [0.45496384, 0.54503616],
       [0.85975802, 0.14024198],
       [0.65092423, 0.34907577],
       [0.07546167, 0.92453833],
       [0.21657119, 0.78342881],
       [0.50509394, 0.49490606],
       [0.47921683, 0.52078317],
       [0.86063115, 0.13936885],
       [0.14972345, 0.85027655],
       [0.80700875, 0.19299125],
       [0.87370233, 0.12629767],
       [0.74184915, 0.25815085],
       [0.40862767, 0.59137233],
       [0.48908215, 0.51091785],
       [0.90395917, 0.09604083],
       [0.58707163, 0.41292837],
       [0.18973419, 0.81026581],
       [0.53435188, 0.46564812],
       [0.27382007, 0.72617993],
       [0.16237531, 0.83762469],
       [0.16084989, 0.83915011],
       [0.59088998, 0.40911002],
       [0.58432761, 0.41567239],
       [0.74202751, 0.25797249],
       [0.39621681, 0.60378319],
       [0.86943921, 0.13056079],
       [0.22395302, 0.77604698],
       [0.5048739 , 0.4951261 ],
       [0.49285516, 0.50714484],
       [0.36476666, 0.63523334],
       [0.67537023, 0.32462977],
       [0.87126807, 0.12873193],
       [0.45575362, 0.54424638],
       [0.84682096, 0.15317904],
       [0.51296352, 0.48703648],
       [0.38875689, 0.61124311],
       [0.4634347 , 0.5365653 ],
       [0.18887357, 0.81112643],
       [0.40464123, 0.59535877],
       [0.51352535, 0.48647465],
       [0.58676291, 0.41323709],
       [0.44834903, 0.55165097],
       [0.39453246, 0.60546754],
       [0.60654617, 0.39345383],
       [0.86347848, 0.13652152],
       [0.41524232, 0.58475768],
       [0.66728253, 0.33271747],
       [0.63571781, 0.36428219],
       [0.74409049, 0.25590951],
       [0.89839562, 0.10160438],
       [0.44780763, 0.55219237],
       [0.12082505, 0.87917495],
       [0.45450502, 0.54549498],
       [0.34006054, 0.65993946],
       [0.64545338, 0.35454662],
       [0.17019254, 0.82980746],
       [0.68495336, 0.31504664],
       [0.56432679, 0.43567321],
       [0.5299291 , 0.4700709 ],
       [0.1091153 , 0.8908847 ],
       [0.90845834, 0.09154166],
       [0.84139788, 0.15860212],
       [0.89087973, 0.10912027],
       [0.88710388, 0.11289612],
       [0.4190162 , 0.5809838 ],
       [0.38417   , 0.61583   ],
       [0.80602939, 0.19397061],
       [0.47403822, 0.52596178],
       [0.71843705, 0.28156295],
       [0.81228302, 0.18771698],
       [0.89059882, 0.10940118],
       [0.35289351, 0.64710649],
       [0.90418303, 0.09581697],
       [0.51215834, 0.48784166],
       [0.8720802 , 0.1279198 ],
       [0.11402877, 0.88597123],
       [0.12198935, 0.87801065],
       [0.50884751, 0.49115249],
       [0.5178218 , 0.4821782 ],
       [0.87118036, 0.12881964],
       [0.83704356, 0.16295644],
       [0.83355417, 0.16644583],
       [0.47821829, 0.52178171],
       [0.72372124, 0.27627876],
       [0.65856216, 0.34143784],
       [0.64146684, 0.35853316],
       [0.84634182, 0.15365818],
       [0.38624179, 0.61375821],
       [0.78704058, 0.21295942],
       [0.18219066, 0.81780934],
       [0.62201376, 0.37798624],
       [0.57849734, 0.42150266],
       [0.13878093, 0.86121907],
       [0.42148001, 0.57851999],
       [0.49700627, 0.50299373],
       [0.68817059, 0.31182941],
       [0.78931028, 0.21068972],
       [0.7346371 , 0.2653629 ],
       [0.58408847, 0.41591153],
       [0.13466501, 0.86533499],
       [0.60329103, 0.39670897],
       [0.48445952, 0.51554048],
       [0.1659012 , 0.8340988 ],
       [0.82073092, 0.17926908],
       [0.53024001, 0.46975999],
       [0.40474587, 0.59525413],
       [0.74362545, 0.25637455],
       [0.15275755, 0.84724245],
       [0.50870508, 0.49129492],
       [0.67649729, 0.32350271],
       [0.5564554 , 0.4435446 ],
       [0.80519914, 0.19480086],
       [0.85695524, 0.14304476],
       [0.84755328, 0.15244672],
       [0.64916959, 0.35083041],
       [0.42842724, 0.57157276],
       [0.77464578, 0.22535422],
       [0.24199762, 0.75800238],
       [0.10470581, 0.89529419],
       [0.76463525, 0.23536475],
       [0.37953961, 0.62046039],
       [0.07497824, 0.92502176],
       [0.57976805, 0.42023195],
       [0.46543145, 0.53456855],
       [0.82036953, 0.17963047],
       [0.85077909, 0.14922091],
       [0.39656362, 0.60343638],
       [0.31160774, 0.68839226],
       [0.42486268, 0.57513732],
       [0.90665802, 0.09334198],
       [0.10623271, 0.89376729],
       [0.30664084, 0.69335916],
       [0.12218863, 0.87781137],
       [0.5791955 , 0.4208045 ],
       [0.86934622, 0.13065378],
       [0.55072796, 0.44927204],
       [0.83552706, 0.16447294],
       [0.86895155, 0.13104845],
       [0.72431329, 0.27568671],
       [0.45122018, 0.54877982],
       [0.54849313, 0.45150687],
       [0.3878604 , 0.6121396 ],
       [0.30206195, 0.69793805],
       [0.45539993, 0.54460007],
       [0.80818362, 0.19181638],
       [0.85703627, 0.14296373],
       [0.90341191, 0.09658809],
       [0.15570248, 0.84429752],
       [0.04845067, 0.95154933],
       [0.49987478, 0.50012522],
       [0.25024703, 0.74975297],
       [0.74954337, 0.25045663],
       [0.39280716, 0.60719284],
       [0.88568391, 0.11431609],
       [0.86933215, 0.13066785],
       [0.6600687 , 0.3399313 ],
       [0.90646011, 0.09353989],
       [0.30356796, 0.69643204],
       [0.85706834, 0.14293166],
       [0.33278066, 0.66721934],
       [0.07256288, 0.92743712],
       [0.73686319, 0.26313681]])

In [72]:
predict = probs[:,1]

In [73]:
predict

array([0.18601715, 0.14409789, 0.54748636, 0.89217861, 0.58479988,
       0.49431367, 0.74144224, 0.51459903, 0.35103137, 0.5936703 ,
       0.12633936, 0.58061019, 0.38330222, 0.13161122, 0.15741924,
       0.51803554, 0.79274785, 0.83542068, 0.61386682, 0.28779868,
       0.81115909, 0.18043614, 0.53635013, 0.79531773, 0.10238514,
       0.15338953, 0.84491697, 0.43575991, 0.64135999, 0.79653321,
       0.54741338, 0.63031966, 0.17454491, 0.35970705, 0.70862192,
       0.68062597, 0.89254338, 0.39374572, 0.81588133, 0.83363718,
       0.55753078, 0.79817404, 0.55168747, 0.20701272, 0.59613435,
       0.14091549, 0.28371955, 0.84677924, 0.14774487, 0.72168511,
       0.86687445, 0.88969275, 0.87363518, 0.67929348, 0.21574695,
       0.4749856 , 0.10882634, 0.47603263, 0.91480236, 0.14246105,
       0.83982348, 0.87024015, 0.52348457, 0.37547478, 0.15442184,
       0.86151082, 0.08387208, 0.90089303, 0.7348183 , 0.13404148,
       0.8880941 , 0.67881089, 0.63334303, 0.22593825, 0.14720038,
       0.18719366, 0.13055284, 0.84932569, 0.48789504, 0.17263543,
       0.12340246, 0.38831606, 0.78390674, 0.79898661, 0.59901472,
       0.62660008, 0.88692196, 0.80526087, 0.49095542, 0.18547702,
       0.23535825, 0.81082378, 0.1763775 , 0.27061359, 0.15875686,
       0.5641606 , 0.45631983, 0.67830562, 0.15734737, 0.12589337,
       0.81856073, 0.6114305 , 0.61321574, 0.57781966, 0.85259832,
       0.69396456, 0.5276552 , 0.9312586 , 0.3585637 , 0.90285201,
       0.3179588 , 0.1374244 , 0.87405279, 0.60578271, 0.59888379,
       0.15991466, 0.49846695, 0.71350921, 0.464654  , 0.16574632,
       0.87196402, 0.23356732, 0.87704084, 0.86657354, 0.19120314,
       0.5625354 , 0.38915132, 0.10821381, 0.64498106, 0.52960233,
       0.1961429 , 0.5050924 , 0.89396621, 0.12683433, 0.32994586,
       0.82619673, 0.18418195, 0.3290811 , 0.13239394, 0.43901581,
       0.81922653, 0.79453728, 0.40676363, 0.85057089, 0.46138582,
       0.34647421, 0.22116923, 0.76222439, 0.59411973, 0.91809707,
       0.81033343, 0.51168561, 0.76256381, 0.49326953, 0.68510697,
       0.20408376, 0.56950806, 0.66638262, 0.91560591, 0.46371043,
       0.20245579, 0.90952494, 0.81043248, 0.63166577, 0.58587026,
       0.88330181, 0.40266761, 0.1331617 , 0.56650444, 0.80838681,
       0.68738914, 0.39496858, 0.18225219, 0.46166984, 0.27782751,
       0.70954936, 0.52215716, 0.17490168, 0.5196655 , 0.6948825 ,
       0.81455089, 0.34053853, 0.86073867, 0.40563509, 0.31633265,
       0.85090389, 0.26276043, 0.85057216, 0.80960462, 0.5081164 ,
       0.84786065, 0.12395943, 0.23451984, 0.86116495, 0.65274568,
       0.85853007, 0.52584872, 0.17323141, 0.35592952, 0.34145773,
       0.46697692, 0.45355595, 0.53133567, 0.11088409, 0.18552114,
       0.62076158, 0.16287193, 0.74463695, 0.49622862, 0.54091038,
       0.60005267, 0.82020711, 0.71222674, 0.86884529, 0.19342157,
       0.76131686, 0.18396866, 0.82528447, 0.301033  , 0.35061373,
       0.24496583, 0.95165675, 0.61401761, 0.86329242, 0.85326268,
       0.49044286, 0.14198743, 0.3521055 , 0.63426924, 0.39781008,
       0.22803388, 0.73360592, 0.70052395, 0.18467812, 0.57883698,
       0.77029331, 0.11499778, 0.20363511, 0.54503616, 0.14024198,
       0.34907577, 0.92453833, 0.78342881, 0.49490606, 0.52078317,
       0.13936885, 0.85027655, 0.19299125, 0.12629767, 0.25815085,
       0.59137233, 0.51091785, 0.09604083, 0.41292837, 0.81026581,
       0.46564812, 0.72617993, 0.83762469, 0.83915011, 0.40911002,
       0.41567239, 0.25797249, 0.60378319, 0.13056079, 0.77604698,
       0.4951261 , 0.50714484, 0.63523334, 0.32462977, 0.12873193,
       0.54424638, 0.15317904, 0.48703648, 0.61124311, 0.5365653 ,
       0.81112643, 0.59535877, 0.48647465, 0.41323709, 0.55165097,
       0.60546754, 0.39345383, 0.13652152, 0.58475768, 0.33271747,
       0.36428219, 0.25590951, 0.10160438, 0.55219237, 0.87917495,
       0.54549498, 0.65993946, 0.35454662, 0.82980746, 0.31504664,
       0.43567321, 0.4700709 , 0.8908847 , 0.09154166, 0.15860212,
       0.10912027, 0.11289612, 0.5809838 , 0.61583   , 0.19397061,
       0.52596178, 0.28156295, 0.18771698, 0.10940118, 0.64710649,
       0.09581697, 0.48784166, 0.1279198 , 0.88597123, 0.87801065,
       0.49115249, 0.4821782 , 0.12881964, 0.16295644, 0.16644583,
       0.52178171, 0.27627876, 0.34143784, 0.35853316, 0.15365818,
       0.61375821, 0.21295942, 0.81780934, 0.37798624, 0.42150266,
       0.86121907, 0.57851999, 0.50299373, 0.31182941, 0.21068972,
       0.2653629 , 0.41591153, 0.86533499, 0.39670897, 0.51554048,
       0.8340988 , 0.17926908, 0.46975999, 0.59525413, 0.25637455,
       0.84724245, 0.49129492, 0.32350271, 0.4435446 , 0.19480086,
       0.14304476, 0.15244672, 0.35083041, 0.57157276, 0.22535422,
       0.75800238, 0.89529419, 0.23536475, 0.62046039, 0.92502176,
       0.42023195, 0.53456855, 0.17963047, 0.14922091, 0.60343638,
       0.68839226, 0.57513732, 0.09334198, 0.89376729, 0.69335916,
       0.87781137, 0.4208045 , 0.13065378, 0.44927204, 0.16447294,
       0.13104845, 0.27568671, 0.54877982, 0.45150687, 0.6121396 ,
       0.69793805, 0.54460007, 0.19181638, 0.14296373, 0.09658809,
       0.84429752, 0.95154933, 0.50012522, 0.74975297, 0.25045663,
       0.60719284, 0.11431609, 0.13066785, 0.3399313 , 0.09353989,
       0.69643204, 0.14293166, 0.66721934, 0.92743712, 0.26313681])

In [74]:
probs_df = pd.DataFrame(predict)

In [75]:
# Defifinmos un umbral para cambiarlo del 50% a uno mas aproiado al problema de analisis
t= 0.2 # esto significara que todos los pacientes que tengan una probabilidad mayor seran 
# diagnosticados con Anormalidad de la presión arterial
probs_df["Prediccion"] = np.where(probs_df[0] >= t,1,0)
# o sea que si la probabilidad es mayor que 0.2 que le asigne 1 a esta nueva columna
#de lo contrario que le asigne 0
#ahora agregamos una columna mas con el valor real de set de prueba y_test
probs_df["Valor_real"] = list(y_test)

In [76]:
probs_df.head(10)#Los 0 0 y 1 1 son buenos

          0  Prediccion  Valor_real
0  0.186017           0           0
1  0.144098           0           0
2  0.547486           1           0
3  0.892179           1           1
4  0.584800           1           0
5  0.494314           1           1
6  0.741442           1           1
7  0.514599           1           1
8  0.351031           1           0
9  0.593670           1           0

In [77]:
pd.crosstab(probs_df["Valor_real"],probs_df["Prediccion"])

Prediccion   0    1
Valor_real
0           74  129
1           14  183